set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc" # Needs this line also to overrides the default color

set -s escape-time 0

set-option -g focus-events on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
# set -g status-right "Leaked IP: 192.168.1.69 | Tea: 20 °C | Suffering Since: 4D | Office Ends In: 8hrs"
set -g status-style 'bg=#333333 fg=#5eacd3'

# move the tmux status line to the top of the terminal
set-option -g status-position bottom
set-option -g status-right ""

bind-key -r f run-shell "~/.config/tmux-sessionizer/tmux-sessionizer"
bind-key -r M-h run-shell "tmux neww tmux-sessionizer -s 0"
bind-key -r M-t run-shell "tmux neww tmux-sessionizer -s 1"
bind-key -r M-n run-shell "tmux neww tmux-sessionizer -s 2"
bind-key -r M-s run-shell "tmux neww tmux-sessionizer -s 3"
