set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc" # Needs this line also to overrides the default color

set -s escape-time 0

set-option -g focus-events on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
# set -g status-right "Leaked IP: 192.168.1.69 | Tea: 20 °C | Suffering Since: 4D | Office Ends In: 8hrs"
set -g status-style 'bg=#333333 fg=#5eacd3'

set-option -g status-position bottom

bind-key -r f run-shell "~/.config/tmux-sessionizer/tmux-sessionizer"

set -g base-index 1
